// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── PROJET : copa-ecole ────────────────────────────────────────────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb2ilgOPQZn9WwLM1jK0yRbeWy1eC4tWY',
    appId: '1:786691292552:web:52b534a326c08d29b04e3d',
    messagingSenderId: '786691292552',
    projectId: 'copa-ecole',
    authDomain: 'copa-ecole.firebaseapp.com',
    storageBucket: 'copa-ecole.firebasestorage.app',
    measurementId: 'G-XFLYQ8RBV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkJqJNltWjuEh-O-9vSqG62OF0BX0fNwE',
    appId: '1:786691292552:android:56df98289b77ea27b04e3d',
    messagingSenderId: '786691292552',
    projectId: 'copa-ecole',
    storageBucket: 'copa-ecole.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb2ilgOPQZn9WwLM1jK0yRbeWy1eC4tWY',
    appId: '1:786691292552:web:52b534a326c08d29b04e3d',
    messagingSenderId: '786691292552',
    projectId: 'copa-ecole',
    storageBucket: 'copa-ecole.firebasestorage.app',
    iosBundleId: 'com.edutrack.school_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb2ilgOPQZn9WwLM1jK0yRbeWy1eC4tWY',
    appId: '1:786691292552:web:52b534a326c08d29b04e3d',
    messagingSenderId: '786691292552',
    projectId: 'copa-ecole',
    storageBucket: 'copa-ecole.firebasestorage.app',
    iosBundleId: 'com.edutrack.school_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb2ilgOPQZn9WwLM1jK0yRbeWy1eC4tWY',
    appId: '1:786691292552:web:52b534a326c08d29b04e3d',
    messagingSenderId: '786691292552',
    projectId: 'copa-ecole',
    authDomain: 'copa-ecole.firebaseapp.com',
    storageBucket: 'copa-ecole.firebasestorage.app',
    measurementId: 'G-XFLYQ8RBV6',
  );
}
